// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXWQPCQS0eIzBxXWU-G7ZEtRFvcOJ0Mik',
    appId: '1:717324024964:web:3d28041d6fb1fef61516d1',
    messagingSenderId: '717324024964',
    projectId: 'tic-tac-toe-863d7',
    authDomain: 'tic-tac-toe-863d7.firebaseapp.com',
    databaseURL: 'https://tic-tac-toe-863d7-default-rtdb.firebaseio.com',
    storageBucket: 'tic-tac-toe-863d7.appspot.com',
    measurementId: 'G-QRLC8PCF33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbfTC6Oun7FizkMd3U1j5nsNUzGuUe-QM',
    appId: '1:717324024964:android:fffc27f38f3c098a1516d1',
    messagingSenderId: '717324024964',
    projectId: 'tic-tac-toe-863d7',
    databaseURL: 'https://tic-tac-toe-863d7-default-rtdb.firebaseio.com',
    storageBucket: 'tic-tac-toe-863d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwBRJ2vlFQjiY6nAIDe7aKWfW4ErRyVsA',
    appId: '1:717324024964:ios:4657e4ecfe233c1f1516d1',
    messagingSenderId: '717324024964',
    projectId: 'tic-tac-toe-863d7',
    databaseURL: 'https://tic-tac-toe-863d7-default-rtdb.firebaseio.com',
    storageBucket: 'tic-tac-toe-863d7.appspot.com',
    iosBundleId: 'com.example.ticTacToe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwBRJ2vlFQjiY6nAIDe7aKWfW4ErRyVsA',
    appId: '1:717324024964:ios:56b8c0147f8e726d1516d1',
    messagingSenderId: '717324024964',
    projectId: 'tic-tac-toe-863d7',
    databaseURL: 'https://tic-tac-toe-863d7-default-rtdb.firebaseio.com',
    storageBucket: 'tic-tac-toe-863d7.appspot.com',
    iosBundleId: 'com.example.ticTacToe.RunnerTests',
  );
}
